spring:
  #Postgresql properties
  datasource:
    url: jdbc:postgresql://192.168.1.18:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  #RabbitMQ
  rabbitmq:
    host: 192.168.1.18
    port: 5672
    username: guest
    password: guest

  #Kafka
  kafka:
    template:
      default-topic: library-events
    producer:
      bootstrap-servers: 192.168.1.18:9092, 192.168.1.18:9093, 192.168.1.18:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    admin:
      properties:
        bootstrap.servers: 192.168.1.18:9092, 192.168.1.18:9093, 192.168.1.18:9094