spring:
  #Postgresql properties
  datasource:
    url: jdbc:postgresql://192.168.1.20:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  #MongoDB properties
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: neel
      port: 27017
      host: 192.168.1.20
      auto-index-creation: true
  #JPA properties
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  #RabbitMQ
  rabbitmq:
    host: 192.168.1.20
    port: 5672
    username: guest
    password: guest

